# Generated by Django 5.2.9 on 2025-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
